export const generateLaTeXResume = (extractedText) => {
  // In a real application, we would use an LLM or a sophisticated parser to extract 
  // sections like Education, Experience, Skills from the OCR text.
  // For this demonstration, we'll try to split the text roughly and fill the template.
  
  const cleanText = (text) => text.replace(/[&_%$#^{}\\]/g, '\\$&'); // Escape LaTeX special characters
  
  // Basic heuristic parsing
  const lines = extractedText.split('\n').map(l => l.trim()).filter(l => l.length > 0);
  const name = lines[0] || 'Wareesha Ashraf';
  const email = lines.find(l => l.includes('@')) || 'f223441@cfd.nu.edu.pk';
  const phone = lines.find(l => /[\d-]{7,}/.test(l)) || '+92 311 7714594';

  return `
%-------------------------
% Resume in LaTeX
% Generated by RESUMIND - optimized for ATS & FAANG
%-------------------------

\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\usepackage{fontawesome5}
\\usepackage{multicol}
\\usepackage{xcolor}
\\input{glyphtounicode}

\\pagestyle{fancy}
\\fancyhf{}
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

% Margins
\\addtolength{\\oddsidemargin}{-0.5in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1in}
\\addtolength{\\topmargin}{-.5in}
\\addtolength{\\textheight}{1.0in}

\\urlstyle{same}

\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

% Section formatting
\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large
}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]

% ATS-friendly PDF
\\pdfgentounicode=1

%-------------------------
% Custom commands

\\newcommand{\\resumeItem}[1]{
  \\item\\small{#1 \\vspace{-2pt}}
}

\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{#1} & #2 \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeProjectHeading}[2]{
    \\item
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\small#1 & \\small #2 \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeSubItem}[1]{\\resumeItem{#1}\\vspace{-4pt}}

\\renewcommand\\labelitemii{$\\vcenter{\\hbox{\\tiny$\\bullet$}}$}

\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.15in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}

%-------------------------------------------
%%%%%%  RESUME STARTS HERE  %%%%%%%%%%%%%%%%%%%%

\\begin{document}

%----------HEADING----------
\\begin{center}
    {\\Huge \\scshape \\textbf{${cleanText(name)}}} \\\\ \\vspace{4pt}
    {\\large Software Engineer} \\\\ \\vspace{6pt}
    \\small
    Chiniot, Pakistan \\quad $|$ \\quad
    \\href{mailto:${cleanText(email)}}{\\underline{${cleanText(email)}}} \\quad $|$ \\quad
    ${cleanText(phone)} \\\\ \\vspace{2pt}
    \\href{https://github.com/wareeshayy}{\\underline{github.com/wareeshayy}} \\quad $|$ \\quad
    \\href{https://wareeshaportfolio.netlify.app}{\\underline{Portfolio}} \\quad $|$ \\quad
    \\href{https://linkedin.com/in/wareesha-ashraf}{\\underline{LinkedIn}}
\\end{center}

%-----------RAW EXTRACTED CONTENT (ATS OPTIMIZED)-----------
\\section{Extracted Professional Summary}
  \\resumeSubHeadingListStart
    \\resumeItem{Original content analyzed and formatted for ATS compatibility.}
    ${lines.slice(0, 5).map(line => `\\resumeItem{${cleanText(line)}}`).join('\n    ')}
  \\resumeSubHeadingListEnd

%-----------EXPERIENCE & PROJECTS-----------
\\section{Projects}
  \\resumeSubHeadingListStart
    \\resumeProjectHeading
      {\\textbf{Full Project History}}{2023 -- 2025}
      \\resumeItemListStart
        ${lines.slice(5, 15).map(line => `\\resumeItem{${cleanText(line)}}`).join('\n        ')}
      \\resumeItemListEnd
  \\resumeSubHeadingListEnd

%-----------SKILLS-----------
\\section{Technical Skills}
\\begin{itemize}[leftmargin=0.15in, label={}]
  \\small{\\item{
    \\textbf{Extracted Skills: } ${lines.slice(lines.length - 10).map(l => cleanText(l)).join(', ')}
  }}
\\end{itemize}

\\end{document}
  `.trim();
};
